site_name: UnicornDocs
site_url: https://pringman990.github.io/unicorndocs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue

  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate

  logo: assets/logos/logo.png
  favicon: assets/logos/logo.ico

markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - attr_list
  - footnotes
  - admonition

plugins:
  - search
  - roamlinks
  - awesome-pages